### ISSUE TITLE
FluentBit version upgrade

### ISSUE THREAD

**Issue by bas-ie** [dasmeta/terraform-aws-eks#108]
Hello! Very useful modules, thanks.

Would there be any appetite for a PR that allows specifying the FluentBit helm chart version as an input? Or just upgrading it. The up-to-date release is 0.47.10, corresponding to FluentBit 3.1.9.

**Comment by mrdntgrn** [comment]
hi @richchurcher, good to hear that you use the module, thank you!
we usually do upgrade of underlying modules with eks default version upgrade to have compatible operator/controller versions, and we have plans to upgrade the current eks default version from 1.27 to at least 1.28 in near future,
meanwhile feel free to contribute on project by makeing change/fix and opening PR

**Comment by mrdntgrn** [comment]
hi @bas-ie , we got upgraded the module and components and now fluentbit is on 0.48.1 chart version(this is also set to be configurable via variable named `chart_version` variable

**Comment by bas-ie** [comment]
Thanks!
